# -*- coding: utf-8 -*-
"""CircularSegmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyNnWU6H0S3-75aHL50eaTPoSuB-olAH
"""

!pip install pycocotools

!rm -rf /content/coco

!mkdir -p /content

import os

coco_dir = '/content/coco'
os.makedirs(coco_dir, exist_ok=True)

img_zip_url = 'http://images.cocodataset.org/zips/train2017.zip'
ann_zip_url = 'http://images.cocodataset.org/annotations/annotations_trainval2017.zip'

if not os.path.exists(os.path.join(coco_dir, 'train2017')):
    print("Downloading COCO train2017 images...")
    !wget -q --show-progress -O {coco_dir}/train2017.zip {img_zip_url}
    print("Extracting train2017 images...")
    !unzip -q {coco_dir}/train2017.zip -d {coco_dir}
else:
    print("train2017 images already downloaded and extracted.")

if not os.path.exists(os.path.join(coco_dir, 'annotations')):
    print("Downloading COCO annotations...")
    !wget -q --show-progress -O {coco_dir}/annotations_trainval2017.zip {ann_zip_url}
    print("Extracting annotations...")
    !unzip -q {coco_dir}/annotations_trainval2017.zip -d {coco_dir}
else:
    print("Annotations already downloaded and extracted.")

print("Image folder contains:", len(os.listdir(os.path.join(coco_dir, 'train2017'))), "images")
print("Annotations available:", os.listdir(os.path.join(coco_dir, 'annotations')))

"""# Directory Validation for COCO Images

This cell verifies the presence of the COCO image directory (train2017) and displays the first few image filenames to ensure that the dataset was downloaded and extracted correctly. It's a quick sanity check before proceeding with image processing.
"""

import os

image_dir = '/content/coco/train2017/'
print("Exists?", os.path.exists(image_dir))
print("Files in dir:", os.listdir(image_dir)[:5])

"""# Importing Dependencies & Setting Seeds for Reproducibility

This cell imports all necessary libraries for the project, including image processing (cv2), visualization (matplotlib), data handling (numpy, pandas), and COCO dataset utilities (pycocotools). It also sets up TensorFlow and Keras modules for potential model integration. To ensure consistent results across runs, random seeds are fixed for both NumPy and TensorFlow.
"""

import os
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

from pycocotools.coco import COCO

import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import GlobalMaxPooling2D, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

np.random.seed(42)
tf.random.set_seed(42)

"""# Filtering and Preprocessing Circular Object Annotations from COCO

This cell extracts and preprocesses images containing ‘sports ball’ objects from the COCO dataset—chosen due to their circular shape. After initializing the COCO API, it fetches relevant image and annotation IDs, then iteratively:

    - Loads images and corresponding segmentation masks.
    - Converts polygon-based masks to binary masks.
    - Filters out small annotations (area < 1000).
    - Resizes images and masks to 224×224 resolution.
    - Normalizes grayscale images and reshapes them for model compatibility.

The final output includes clean image-mask pairs focused on circular object segmentation, ready for further analysis or model training.








"""

from pycocotools.coco import COCO
import cv2
import os
import numpy as np
import random

ann_path = '/content/coco/annotations/instances_train2017.json'
image_dir = '/content/coco/train2017/'

coco = COCO(ann_path)

target_category = 'sports ball'
catIds = coco.getCatIds(catNms=[target_category])
imgIds = coco.getImgIds(catIds=catIds)

MAX_IMAGES = 10000
random.seed(42)
sampled_imgIds = random.sample(imgIds, min(MAX_IMAGES, len(imgIds)))

def polygon_to_mask(polygon, shape):
    mask = np.zeros(shape, dtype=np.uint8)
    pts = np.array(polygon, np.int32).reshape((-1, 2))
    cv2.fillPoly(mask, [pts], 1)
    return mask

img_data = []
mask_data = []

MIN_AREA = 1000

for img_id in sampled_imgIds:
    img_info = coco.loadImgs(img_id)[0]
    anns = coco.loadAnns(coco.getAnnIds(imgIds=img_id, catIds=catIds, iscrowd=False))
    if len(anns) == 0:
        continue

    img_path = os.path.join(image_dir, img_info['file_name'])
    img = cv2.imread(img_path)
    if img is None:
        continue

    img_resized = cv2.resize(img, (224, 224))
    gray = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY) / 255.0
    gray = gray.reshape(224, 224, 1)

    mask_full = np.zeros((img_info['height'], img_info['width']), dtype=np.uint8)
    for ann in anns:
        if 'segmentation' in ann and isinstance(ann['segmentation'], list):
            if ann['area'] < MIN_AREA:
                continue
            for polygon in ann['segmentation']:
                poly_mask = polygon_to_mask(polygon, (img_info['height'], img_info['width']))
                mask_full = np.maximum(mask_full, poly_mask)

    if mask_full.sum() < MIN_AREA:
        continue

    mask_resized = cv2.resize(mask_full, (224, 224), interpolation=cv2.INTER_NEAREST)
    mask_resized = mask_resized.astype(np.float32)
    mask_resized = mask_resized.reshape(224, 224, 1)

    img_data.append(gray)
    mask_data.append(mask_resized)

print(f"Total usable 'sports ball' objects: {len(img_data)}")

"""# Preparing Train-Validation Split for Segmentation Data

This cell organizes the preprocessed image and mask data into NumPy arrays and performs a train-validation split. It uses train_test_split from Scikit-learn to allocate 90% of the data for training and 10% for validation, ensuring reproducibility with a fixed random seed. This structured split helps in evaluating model generalization during training.
"""

import numpy as np
from sklearn.model_selection import train_test_split

X = np.stack(img_data)
masks_array = np.stack(mask_data)

print(f"X shape: {X.shape}")
print(f"masks_array shape: {masks_array.shape}")

X_train, X_val, masks_train, masks_val = train_test_split(
    X, masks_array, test_size=0.1, random_state=42
)

print(f"Train samples: {X_train.shape[0]}, Validation samples: {X_val.shape[0]}")

"""# MobileNetV2-Based Segmentation Model with Dice Loss

This cell defines a custom semantic segmentation model using a MobileNetV2 backbone pretrained on ImageNet. Since our input is grayscale, it is converted to RGB via a Lambda layer. The encoder layers of MobileNetV2 are frozen to retain pretrained features, and a custom decoder is built using progressive UpSampling2D and convolutional blocks to reconstruct the segmentation mask.

The model outputs a single-channel sigmoid-activated mask and is compiled with:

    - Dice Loss (optimized for imbalanced segmentation),
    - Adam optimizer, and
    - Accuracy as a metric.

The model architecture is printed via model.summary() for verification.
"""

import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, UpSampling2D, BatchNormalization, Activation, Lambda
from tensorflow.keras.models import Model
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K

def dice_loss(y_true, y_pred, smooth=1e-6):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return 1 - (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

input_layer = Input(shape=(224, 224, 1))

x = Lambda(lambda x: tf.image.grayscale_to_rgb(x))(input_layer)

backbone = MobileNetV2(input_tensor=x, include_top=False, weights='imagenet')

for layer in backbone.layers[:100]:
    layer.trainable = False

encoder_output = backbone.output

def conv_block(tensor, filters):
    x = Conv2D(filters, 3, padding='same')(tensor)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    return x

x = UpSampling2D()(encoder_output)
x = conv_block(x, 512)

x = UpSampling2D()(x)
x = conv_block(x, 256)

x = UpSampling2D()(x)
x = conv_block(x, 128)

x = UpSampling2D()(x)
x = conv_block(x, 64)

x = UpSampling2D()(x)
x = conv_block(x, 32)

mask_output = Conv2D(1, 1, activation='sigmoid', name='mask_output')(x)

model = Model(inputs=input_layer, outputs=mask_output)

model.compile(
    optimizer=Adam(1e-4),
    loss=dice_loss,
    metrics=['accuracy']
)

model.summary()

"""# Model Training with Checkpoints, Learning Rate Scheduling, and Early Stopping

This cell initiates the training process for the segmentation model with robust training safeguards:

    - EarlyStopping halts training if validation loss stops improving for 6 epochs.
    - ReduceLROnPlateau lowers the learning rate by a factor of 0.5 if performance plateaus,
      helping the model converge better.
    - ModelCheckpoint saves the best-performing model (based on validation loss) for later use.

Training runs for up to 50 epochs with a batch size of 32 and includes real-time validation tracking. All checkpoints are saved under /content/model_checkpoints.
"""

import os
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

checkpoint_dir = '/content/model_checkpoints'
os.makedirs(checkpoint_dir, exist_ok=True)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=6,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    min_lr=1e-6,
    verbose=1
)

model_chk = ModelCheckpoint(
    filepath=os.path.join(checkpoint_dir, 'best_model.h5'),
    monitor='val_loss',
    save_best_only=True,
    save_weights_only=False,
    verbose=1
)

history = model.fit(
    X_train,
    masks_train,
    validation_data=(X_val, masks_val),
    epochs=50,
    batch_size=32,
    shuffle=True,
    callbacks=[early_stop, reduce_lr, model_chk],
    verbose=1
)

"""# Circle Extraction & Visualization from Segmentation Masks

This cell performs a post-processing step to detect circular shapes from segmentation masks and visually confirm the accuracy of the segmentation.

Key functionalities include:

1. extract_all_circle_params: Detects connected components in the binary mask and fits a minimum enclosing circle for each. It returns both pixel-level and normalized coordinates (center and radius).

2. visualize_mask_and_circle: Randomly samples a few images and displays:

       - The original image with overlaid detected circles,
       - The ground truth mask,
       - A mask reconstructed using predicted circle parameters,
       - A clean canvas showing centers and radii with annotated circle overlays.

This step ensures that the model not only segments circular objects but also enables accurate geometric interpretation, which is essential for downstream tasks like tracking or measurements.








"""

import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import numpy as np
import cv2

D_FACTOR = 15

def extract_all_circle_params(mask):
    h, w = mask.shape[:2]
    mask_gray = (mask[:, :, 0] * 255).astype(np.uint8)

    num_labels, labels = cv2.connectedComponents(mask_gray)

    circles = []
    for label in range(1, num_labels):
        component_mask = (labels == label).astype(np.uint8) * 255
        contours, _ = cv2.findContours(component_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if len(contours) == 0:
            continue
        cnt = contours[0]
        (x_pixel, y_pixel), r_pixel = cv2.minEnclosingCircle(cnt)

        x_norm = (x_pixel - w/2) / (w/2)
        y_norm = (y_pixel - h/2) / (h/2)
        r_norm = r_pixel / (np.mean([h, w]) / D_FACTOR)

        circles.append({
            'x_pixel': int(x_pixel),
            'y_pixel': int(y_pixel),
            'r_pixel': int(r_pixel),
            'x_norm': x_norm,
            'y_norm': y_norm,
            'r_norm': r_norm
        })

    return circles


def visualize_mask_and_circle(X, masks, num_samples=5):
    idxs = np.random.choice(len(X), num_samples, replace=False)
    fig, axes = plt.subplots(num_samples, 4, figsize=(22, 5 * num_samples))

    for i, idx in enumerate(idxs):
        img = X[idx, :, :, 0]
        mask = masks[idx]

        h, w = img.shape
        circles = extract_all_circle_params(mask)

        axes[i, 0].imshow(img, cmap='gray')
        for c in circles:
            circ = Circle((c['x_pixel'], c['y_pixel']), c['r_pixel'], edgecolor='red', facecolor='none', lw=2)
            axes[i, 0].add_patch(circ)
        axes[i, 0].set_title("Original Image + All Circles")
        axes[i, 0].set_xlim(0, w)
        axes[i, 0].set_ylim(h, 0)

        axes[i, 1].imshow(mask[:, :, 0], cmap='gray')
        axes[i, 1].set_title("Ground Truth Mask")
        axes[i, 1].set_xlim(0, w)
        axes[i, 1].set_ylim(h, 0)

        pred_mask = np.zeros_like(mask[:, :, 0])
        title_info = []
        for c in circles:
            cv2.circle(pred_mask, (c['x_pixel'], c['y_pixel']), c['r_pixel'], 1, thickness=-1)
            title_info.append(f"({c['x_pixel']},{c['y_pixel']}), r={c['r_pixel']}")
        axes[i, 2].imshow(pred_mask, cmap='gray')
        axes[i, 2].set_title("Predicted Circle Mask\n" + "\n".join(title_info))
        axes[i, 2].set_xlim(0, w)
        axes[i, 2].set_ylim(h, 0)

        white_bg = np.ones_like(img) * 255
        axes[i, 3].imshow(white_bg, cmap='gray')
        axes[i, 3].set_title("Circle Centers + Radius")
        axes[i, 3].set_xlim(0, w)
        axes[i, 3].set_ylim(h, 0)
        axes[i, 3].set_aspect('equal')

        for j, c in enumerate(circles):
            x, y, r = c['x_pixel'], c['y_pixel'], c['r_pixel']
            axes[i, 3].scatter(x, y, c='red', s=100)
            axes[i, 3].text(x + 5, y, f"({x},{y})", color='red', fontsize=12)
            axes[i, 3].add_patch(Circle((x, y), r, edgecolor='green', facecolor='none', lw=2))
            axes[i, 3].plot([x, x + r], [y, y], color='orange', lw=2)
            axes[i, 3].text(x + r / 2, y - 10, f"r={r}", color='orange', fontsize=12, ha='center')

    plt.tight_layout()
    plt.show()

visualize_mask_and_circle(X_val, masks_val, num_samples=5)

"""# Validation Performance Evaluation of the Segmentation Model

This cell evaluates the trained segmentation model on the validation dataset, computing the final loss and accuracy metrics. These results summarize the model’s ability to generalize and accurately predict masks on unseen data, providing a quantitative measure of segmentation quality before deployment or further analysis.








"""

val_results = model.evaluate(
    X_val,
    masks_val,
    verbose=0
)

print(f"Final Validation Loss: {val_results[0]:.4f}")
print(f"Final Validation Accuracy: {val_results[1]:.4f}")

"""# Training and Validation Performance Visualization

This cell visualizes the model’s learning progress by plotting loss and accuracy curves over training epochs. The loss subplot shows how the binary cross-entropy loss evolves, indicating improvements in segmentation quality. The accuracy subplot tracks the model's correctness in pixel-wise predictions on both training and validation sets. These plots help diagnose underfitting, overfitting, or convergence issues during training.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss', marker='o')
plt.plot(history.history['val_loss'], label='Validation Loss', marker='o')
plt.title('Loss Curve')
plt.xlabel('Epochs')
plt.ylabel('Binary Cross-Entropy Loss')
plt.grid(True)
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Training Accuracy', marker='o')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', marker='o')
plt.title('Accuracy Curve')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

"""# Detailed Pixel-Level Segmentation Metrics and Visualization

This cell provides an in-depth evaluation of the segmentation model's pixel-wise performance on the validation set:

    - IoU (Intersection over Union) and Dice Coefficient quantify overlap
      quality between predicted and ground truth masks.

    - A classification report shows precision, recall, f1-score for each pixel
      class (background vs object).

    - The confusion matrix heatmap visualizes true vs predicted pixel counts,
      aiding error analysis.

    - The ROC curve with AUC score illustrates the model’s ability to
      discriminate pixels at varying classification thresholds.

Together, these metrics give a comprehensive understanding of segmentation accuracy and model robustness beyond just loss and accuracy values.
"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve
import numpy as np

def iou_score(y_true, y_pred):
    intersection = np.sum(y_true * y_pred)
    union = np.sum(y_true) + np.sum(y_pred) - intersection
    return intersection / union if union != 0 else 0

def dice_coef(y_true, y_pred):
    intersection = 2 * np.sum(y_true * y_pred)
    denominator = np.sum(y_true) + np.sum(y_pred)
    return intersection / denominator if denominator != 0 else 0

y_pred_prob = model.predict(X_val, verbose=0)
y_pred_bin = (y_pred_prob > 0.5).astype(np.uint8)

y_true_flat = masks_val.flatten()
y_pred_flat = y_pred_bin.flatten()
y_pred_prob_flat = y_pred_prob.flatten()

iou = iou_score(y_true_flat, y_pred_flat)
dice = dice_coef(y_true_flat, y_pred_flat)

print(f"Pixel-wise IoU: {iou:.4f}")
print(f"Pixel-wise Dice Coefficient: {dice:.4f}")
print("\nClassification Report (Pixel-wise):")
print(classification_report(y_true_flat, y_pred_flat, digits=4))

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.subplots_adjust(wspace=0.3)

cm = confusion_matrix(y_true_flat, y_pred_flat)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Pred 0', 'Pred 1'], yticklabels=['True 0', 'True 1'], ax=axes[0])
axes[0].set_title("Confusion Matrix (Pixel Level)")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

auc_score = roc_auc_score(y_true_flat, y_pred_prob_flat)
fpr, tpr, thresholds = roc_curve(y_true_flat, y_pred_prob_flat)
axes[1].plot(fpr, tpr, label=f"AUC = {auc_score:.4f}")
axes[1].plot([0, 1], [0, 1], 'k--')
axes[1].set_xlabel("False Positive Rate")
axes[1].set_ylabel("True Positive Rate")
axes[1].set_title("ROC Curve (Pixel Level)")
axes[1].legend(loc="lower right")
axes[1].grid(True)

plt.tight_layout()
plt.show()